### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by 11jo**
At last...

Thanks for your updates Jastey !

### CODE REVIEW

**Comment by Gitjas** [comment]
Thank you! I added info to the readme - do you want to update it, too?

**Comment by Gitjas** [comment]
@11jo  I'm pinging all translators (or who provided them): v14 will have new lines: https://github.com/Gibberlings3/Jasteys_SoD_Tweakpack/commit/c0bf06e58cbfa18681cfa49e284ee573e7605276
Greetings!

**Comment by 11jo** [comment]
> @11jo I'm pinging all translators (or who provided them): v14 will have new lines: [c0bf06e](https://github.com/Gibberlings3/Jasteys_SoD_Tweakpack/commit/c0bf06e58cbfa18681cfa49e284ee573e7605276) Greetings!

Hello @Gitjas !

There is a typo in [setup.tra](https://github.com/Gibberlings3/Jasteys_SoD_Tweakpack/blob/a29cf14d173404eabe7d489b953aaf41e11a7ff2/c%23sodtweaks/translations/english/setup.tra#L41-L44),  `@1030` is duplicated.

**Comment by Gitjas** [comment]
Thank you for spotting that!
I'll probably move the second line down to @1033. I can do that myself if I have the translations.

**Pull request merged**
