### PR TITLE
add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by Lzw104522773**
add Simplified Chinese translation

### CODE REVIEW

**Comment by Gitjas** [comment]
setup.tra seems to be in utf8. I'd need the file in ANSI, as well.

**Comment by Lzw104522773** [comment]
setup.tra is in utf8，there is no problem.I have tested using the latest version of weiduexe on BG1EE and EET.

**Comment by Gitjas** [comment]
Oh, you are right. I mixed that up. Thanks!

**Comment by Gitjas** [comment]
@Lzw104522773 there is new lines for the upcoming v14: https://github.com/Gibberlings3/Jasteys_SoD_Tweakpack/commit/c0bf06e58cbfa18681cfa49e284ee573e7605276

**Comment by MephistoSatanDevil** [comment]
> setup.tra seems to be in utf8. I'd need the file in ANSI, as well.

https://github.com/Gibberlings3/Jasteys_SoD_Tweakpack/pull/42
done.

**Pull request merged**
